apiVersion: apps/v1
kind: Deployment
metadata:
  name: heavy-jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heavy-jupyter
  template:
    metadata:
      labels:
        app: heavy-jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/scipy-notebook
        env:
        - name: JUPYTER_TOKEN
          value: "1234"
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "3Gi"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: heavy-jupyter-svc
spec:
  type: NodePort
  selector:
    app: heavy-jupyter
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30030
