apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: light-jupyter
  template:
    metadata:
      labels:
        app: light-jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/base-notebook
        env:
        - name: JUPYTER_TOKEN
          value: "1234"
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "300m"
            memory: "1Gi"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: light-jupyter-svc
spec:
  type: NodePort
  selector:
    app: light-jupyter
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30088
---

